---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site/content/ergo
  label: Ergo
  create: all
  match: "**/*"
- type: directory
  path: site/content/physio
  label: Physio
  create: all
  match: "**/*"
- type: directory
  path: site/content/logo
  label: Logo
  create: all
  match: "**/*"
- type: directory
  path: site/content/therapists
  label: Therapists
  create: all
  match: "**/*"
- type: directory
  path: site/content/doctors
  label: Doctors
  create: all
  match: "**/*"
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run cms
version: 0.63.2
